### ISSUE TITLE
I'm getting an error in generate

### ISSUE THREAD

**Issue by juusechec** [SwissTierrasColombia/Asistente-LADM-COL-docs#5]
I do the next steps:
```sh
jorge@ulises:~/workspace 4611 15:32:07 $ git clone -b master --depth 10 https://github.com/AgenciaImplementacion/Asistente-LADM_COL-docs
Cloning into 'Asistente-LADM_COL-docs'...
remote: Counting objects: 161, done.
remote: Compressing objects: 100% (94/94), done.
remote: Total 161 (delta 77), reused 139 (delta 58), pack-reused 0
Receiving objects: 100% (161/161), 3.69 MiB | 3.17 MiB/s, done.
Resolving deltas: 100% (77/77), done.

jorge@ulises:~/workspace/Asistente-LADM_COL-docs 4613 15:32:37 $ ./generate.sh 
+ cd src
+ sphinx-versioning build src build/en/html --show-banner -- -D language=en
=> Gathering info about the remote git repository...
=> Getting list of all remote branches/tags...
=> Found: fix_deploy master no_underscore server 0.0.1 0.0.2
=> Need to fetch from remote...
=> With docs: master 0.0.1 0.0.2
=> Root ref is: master
=> Banner main ref is: master
=> Pre-running Sphinx to collect versions' master_doc and other info.
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/sphinxcontrib/versioning/sphinx_.py", line 205, in _build
    result = build_main(argv)
  File "/usr/local/lib/python3.6/dist-packages/sphinx/__init__.py", line 81, in build_main
    return build.build_main(argv[1:])  # skip first argument to adjust arguments (refs: #4615)
NameError: name 'build' is not defined
=> sphinx-build failed for branch/tag: master
Failure
```

What am I doing wrong?

**Comment by juusechec** [comment]
I've solved with steps:

```sh
sudo pip3 install --upgrade pip
sudo pip3 uninstall sphinx
sudo pip3 uninstall sphinx_rtd_theme
sudo pip3 uninstall sphinxcontrib-images
sudo pip3 uninstall sphinxcontrib-versioning
```

Then:
```sh
sudo pip3 install -r requirements.txt
```
